
# Rebind omarchy defaults

# Key bindings
unbind = SUPER, K
bindd = SUPER CTRL, K, Show key bindings, exec, omarchy-menu-keybindings

# Toggle split (conflicts with neovim navigation binding)
unbind = SUPER, J
bindd = SUPER CTRL, J, Toggle split, togglesplit, # dwindle

# Move focus with SUPER + hjkl keys
bindd = SUPER, h, Move focus left, movefocus, l
bindd = SUPER, j, Move focus down, movefocus, d
bindd = SUPER, k, Move focus up, movefocus, u
bindd = SUPER, l, Move focus right, movefocus, r

bind = SUPER, h, exec, hyprctl dispatch focusgroup left
bind = SUPER, l, exec, hyprctl dispatch focusgroup right
bind = SUPER, k, exec, hyprctl dispatch focusgroup up
bind = SUPER, j, exec, hyprctl dispatch focusgroup down

# Join groups

# Unbind toggling between dwindle and scrolling layouts
unbind = SUPER, L

bindd = SUPER ALT, h, Move window to group on left, moveintogroup, l
bindd = SUPER ALT, l, Move window to group on right, moveintogroup, r
bindd = SUPER ALT, UP, Move window to group on top, moveintogroup, u
bindd = SUPER ALT, DOWN, Move window to group on bottom, moveintogroup, d


# Window manipulation & navigation
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, j, movewindow, d
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, l, movewindow, r

bind = SUPER, x, killactive,
bind = SUPER, TAB, cyclenext,
bind = SUPER, t, togglegroup,



